### ISSUE TITLE
thermoml-update-mirror throws http error

### ISSUE THREAD

**Issue by ocmadin** [choderalab/thermopyl#32]
Attempting to create a new local mirror using `thermoml-update-mirror`, I get the following error message: 
```
Downloading http://trc.nist.gov/ThermoML/JCT.tgz
Traceback (most recent call last):
  File "/home/owenmadin/anaconda3/envs/thermopyl/bin/thermoml-update-mirror", line 9, in <module>
    load_entry_point('thermopyl==1.0.1', 'console_scripts', 'thermoml-update-mirror')()
  File "/home/owenmadin/anaconda3/envs/thermopyl/lib/python2.7/site-packages/thermopyl-1.0.1-py2.7.egg/thermopyl/scripts/update_archive.py", line 9, in main
    thermopyl.update_archive()
  File "/home/owenmadin/anaconda3/envs/thermopyl/lib/python2.7/site-packages/thermopyl-1.0.1-py2.7.egg/thermopyl/archivetools.py", line 51, in update_archive
    file.retrieve(url, local_filename)
  File "/home/owenmadin/anaconda3/envs/thermopyl/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/home/owenmadin/anaconda3/envs/thermopyl/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/home/owenmadin/anaconda3/envs/thermopyl/lib/python2.7/urllib.py", line 364, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/home/owenmadin/anaconda3/envs/thermopyl/lib/python2.7/urllib.py", line 381, in http_error
    return self.http_error_default(url, fp, errcode, errmsg, headers)
  File "/home/owenmadin/anaconda3/envs/thermopyl/lib/python2.7/urllib.py", line 386, in http_error_default
    raise IOError, ('http error', errcode, errmsg, headers)
IOError: ('http error', 301, 'Moved Permanently', <httplib.HTTPMessage instance at 0x7f04c0917b00>)
```

Is this an issue with the websites that `thermopyl` looks for potentially having moved?

**Comment by kyleabeauchamp** [comment]
It is very possible that this has occurred.  @kkroenlein do you recall if there have been any URL changes at your institution?

**Comment by mrshirts** [comment]
@kkroenlein sent a local dump that we probably want to use for now.

**Comment by kkroenlein** [comment]
@kyleabeauchamp I'll check to see, but I thought those should be stable.
